################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Components/net/lwip/lwip-2.1.2/src/core/ipv6/dhcp6.c \
../Components/net/lwip/lwip-2.1.2/src/core/ipv6/ethip6.c \
../Components/net/lwip/lwip-2.1.2/src/core/ipv6/icmp6.c \
../Components/net/lwip/lwip-2.1.2/src/core/ipv6/inet6.c \
../Components/net/lwip/lwip-2.1.2/src/core/ipv6/ip6.c \
../Components/net/lwip/lwip-2.1.2/src/core/ipv6/ip6_addr.c \
../Components/net/lwip/lwip-2.1.2/src/core/ipv6/ip6_frag.c \
../Components/net/lwip/lwip-2.1.2/src/core/ipv6/mld6.c \
../Components/net/lwip/lwip-2.1.2/src/core/ipv6/nd6.c 

OBJS += \
./Components/net/lwip/lwip-2.1.2/src/core/ipv6/dhcp6.o \
./Components/net/lwip/lwip-2.1.2/src/core/ipv6/ethip6.o \
./Components/net/lwip/lwip-2.1.2/src/core/ipv6/icmp6.o \
./Components/net/lwip/lwip-2.1.2/src/core/ipv6/inet6.o \
./Components/net/lwip/lwip-2.1.2/src/core/ipv6/ip6.o \
./Components/net/lwip/lwip-2.1.2/src/core/ipv6/ip6_addr.o \
./Components/net/lwip/lwip-2.1.2/src/core/ipv6/ip6_frag.o \
./Components/net/lwip/lwip-2.1.2/src/core/ipv6/mld6.o \
./Components/net/lwip/lwip-2.1.2/src/core/ipv6/nd6.o 

C_DEPS += \
./Components/net/lwip/lwip-2.1.2/src/core/ipv6/dhcp6.d \
./Components/net/lwip/lwip-2.1.2/src/core/ipv6/ethip6.d \
./Components/net/lwip/lwip-2.1.2/src/core/ipv6/icmp6.d \
./Components/net/lwip/lwip-2.1.2/src/core/ipv6/inet6.d \
./Components/net/lwip/lwip-2.1.2/src/core/ipv6/ip6.d \
./Components/net/lwip/lwip-2.1.2/src/core/ipv6/ip6_addr.d \
./Components/net/lwip/lwip-2.1.2/src/core/ipv6/ip6_frag.d \
./Components/net/lwip/lwip-2.1.2/src/core/ipv6/mld6.d \
./Components/net/lwip/lwip-2.1.2/src/core/ipv6/nd6.d 


# Each subdirectory must supply rules for building sources it contributes
Components/net/lwip/lwip-2.1.2/src/core/ipv6/dhcp6.o: ../Components/net/lwip/lwip-2.1.2/src/core/ipv6/dhcp6.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F107xC -DDEBUG -c -I../Middlewares/LiteOS/kernel/extended/include -I../Middlewares/LiteOS/arch/arm/arm-m/include -I../Components/connectivity/mqtt/MQTTClient-C/src -I../Components/Inc/fs -I../Components/connectivity/mqtt/MQTTClient-C/src/liteOS -I../Components/Inc -I../Middlewares/LiteOS/arch/arm/include -I../Middlewares/LiteOS/kernel/base/include -I../App/Inc -I../Components/net/lwip/lwip_port -I../Components/net/lwip/lwip_port/OS -I../Components/net/lwip/lwip-2.1.2/src/include -I../OS_CONFIG -I../Middlewares/LiteOS/kernel/include -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -I../Core/Inc -I../Hardware/Inc -I../Components/lib/cJSON -I../Components/connectivity/mqtt/MQTTPacket/src -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Components/net/lwip/lwip_port/arch -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Components/net/lwip/lwip-2.1.2/src/core/ipv6/dhcp6.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Components/net/lwip/lwip-2.1.2/src/core/ipv6/ethip6.o: ../Components/net/lwip/lwip-2.1.2/src/core/ipv6/ethip6.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F107xC -DDEBUG -c -I../Middlewares/LiteOS/kernel/extended/include -I../Middlewares/LiteOS/arch/arm/arm-m/include -I../Components/connectivity/mqtt/MQTTClient-C/src -I../Components/Inc/fs -I../Components/connectivity/mqtt/MQTTClient-C/src/liteOS -I../Components/Inc -I../Middlewares/LiteOS/arch/arm/include -I../Middlewares/LiteOS/kernel/base/include -I../App/Inc -I../Components/net/lwip/lwip_port -I../Components/net/lwip/lwip_port/OS -I../Components/net/lwip/lwip-2.1.2/src/include -I../OS_CONFIG -I../Middlewares/LiteOS/kernel/include -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -I../Core/Inc -I../Hardware/Inc -I../Components/lib/cJSON -I../Components/connectivity/mqtt/MQTTPacket/src -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Components/net/lwip/lwip_port/arch -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Components/net/lwip/lwip-2.1.2/src/core/ipv6/ethip6.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Components/net/lwip/lwip-2.1.2/src/core/ipv6/icmp6.o: ../Components/net/lwip/lwip-2.1.2/src/core/ipv6/icmp6.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F107xC -DDEBUG -c -I../Middlewares/LiteOS/kernel/extended/include -I../Middlewares/LiteOS/arch/arm/arm-m/include -I../Components/connectivity/mqtt/MQTTClient-C/src -I../Components/Inc/fs -I../Components/connectivity/mqtt/MQTTClient-C/src/liteOS -I../Components/Inc -I../Middlewares/LiteOS/arch/arm/include -I../Middlewares/LiteOS/kernel/base/include -I../App/Inc -I../Components/net/lwip/lwip_port -I../Components/net/lwip/lwip_port/OS -I../Components/net/lwip/lwip-2.1.2/src/include -I../OS_CONFIG -I../Middlewares/LiteOS/kernel/include -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -I../Core/Inc -I../Hardware/Inc -I../Components/lib/cJSON -I../Components/connectivity/mqtt/MQTTPacket/src -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Components/net/lwip/lwip_port/arch -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Components/net/lwip/lwip-2.1.2/src/core/ipv6/icmp6.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Components/net/lwip/lwip-2.1.2/src/core/ipv6/inet6.o: ../Components/net/lwip/lwip-2.1.2/src/core/ipv6/inet6.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F107xC -DDEBUG -c -I../Middlewares/LiteOS/kernel/extended/include -I../Middlewares/LiteOS/arch/arm/arm-m/include -I../Components/connectivity/mqtt/MQTTClient-C/src -I../Components/Inc/fs -I../Components/connectivity/mqtt/MQTTClient-C/src/liteOS -I../Components/Inc -I../Middlewares/LiteOS/arch/arm/include -I../Middlewares/LiteOS/kernel/base/include -I../App/Inc -I../Components/net/lwip/lwip_port -I../Components/net/lwip/lwip_port/OS -I../Components/net/lwip/lwip-2.1.2/src/include -I../OS_CONFIG -I../Middlewares/LiteOS/kernel/include -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -I../Core/Inc -I../Hardware/Inc -I../Components/lib/cJSON -I../Components/connectivity/mqtt/MQTTPacket/src -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Components/net/lwip/lwip_port/arch -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Components/net/lwip/lwip-2.1.2/src/core/ipv6/inet6.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Components/net/lwip/lwip-2.1.2/src/core/ipv6/ip6.o: ../Components/net/lwip/lwip-2.1.2/src/core/ipv6/ip6.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F107xC -DDEBUG -c -I../Middlewares/LiteOS/kernel/extended/include -I../Middlewares/LiteOS/arch/arm/arm-m/include -I../Components/connectivity/mqtt/MQTTClient-C/src -I../Components/Inc/fs -I../Components/connectivity/mqtt/MQTTClient-C/src/liteOS -I../Components/Inc -I../Middlewares/LiteOS/arch/arm/include -I../Middlewares/LiteOS/kernel/base/include -I../App/Inc -I../Components/net/lwip/lwip_port -I../Components/net/lwip/lwip_port/OS -I../Components/net/lwip/lwip-2.1.2/src/include -I../OS_CONFIG -I../Middlewares/LiteOS/kernel/include -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -I../Core/Inc -I../Hardware/Inc -I../Components/lib/cJSON -I../Components/connectivity/mqtt/MQTTPacket/src -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Components/net/lwip/lwip_port/arch -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Components/net/lwip/lwip-2.1.2/src/core/ipv6/ip6.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Components/net/lwip/lwip-2.1.2/src/core/ipv6/ip6_addr.o: ../Components/net/lwip/lwip-2.1.2/src/core/ipv6/ip6_addr.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F107xC -DDEBUG -c -I../Middlewares/LiteOS/kernel/extended/include -I../Middlewares/LiteOS/arch/arm/arm-m/include -I../Components/connectivity/mqtt/MQTTClient-C/src -I../Components/Inc/fs -I../Components/connectivity/mqtt/MQTTClient-C/src/liteOS -I../Components/Inc -I../Middlewares/LiteOS/arch/arm/include -I../Middlewares/LiteOS/kernel/base/include -I../App/Inc -I../Components/net/lwip/lwip_port -I../Components/net/lwip/lwip_port/OS -I../Components/net/lwip/lwip-2.1.2/src/include -I../OS_CONFIG -I../Middlewares/LiteOS/kernel/include -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -I../Core/Inc -I../Hardware/Inc -I../Components/lib/cJSON -I../Components/connectivity/mqtt/MQTTPacket/src -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Components/net/lwip/lwip_port/arch -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Components/net/lwip/lwip-2.1.2/src/core/ipv6/ip6_addr.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Components/net/lwip/lwip-2.1.2/src/core/ipv6/ip6_frag.o: ../Components/net/lwip/lwip-2.1.2/src/core/ipv6/ip6_frag.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F107xC -DDEBUG -c -I../Middlewares/LiteOS/kernel/extended/include -I../Middlewares/LiteOS/arch/arm/arm-m/include -I../Components/connectivity/mqtt/MQTTClient-C/src -I../Components/Inc/fs -I../Components/connectivity/mqtt/MQTTClient-C/src/liteOS -I../Components/Inc -I../Middlewares/LiteOS/arch/arm/include -I../Middlewares/LiteOS/kernel/base/include -I../App/Inc -I../Components/net/lwip/lwip_port -I../Components/net/lwip/lwip_port/OS -I../Components/net/lwip/lwip-2.1.2/src/include -I../OS_CONFIG -I../Middlewares/LiteOS/kernel/include -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -I../Core/Inc -I../Hardware/Inc -I../Components/lib/cJSON -I../Components/connectivity/mqtt/MQTTPacket/src -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Components/net/lwip/lwip_port/arch -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Components/net/lwip/lwip-2.1.2/src/core/ipv6/ip6_frag.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Components/net/lwip/lwip-2.1.2/src/core/ipv6/mld6.o: ../Components/net/lwip/lwip-2.1.2/src/core/ipv6/mld6.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F107xC -DDEBUG -c -I../Middlewares/LiteOS/kernel/extended/include -I../Middlewares/LiteOS/arch/arm/arm-m/include -I../Components/connectivity/mqtt/MQTTClient-C/src -I../Components/Inc/fs -I../Components/connectivity/mqtt/MQTTClient-C/src/liteOS -I../Components/Inc -I../Middlewares/LiteOS/arch/arm/include -I../Middlewares/LiteOS/kernel/base/include -I../App/Inc -I../Components/net/lwip/lwip_port -I../Components/net/lwip/lwip_port/OS -I../Components/net/lwip/lwip-2.1.2/src/include -I../OS_CONFIG -I../Middlewares/LiteOS/kernel/include -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -I../Core/Inc -I../Hardware/Inc -I../Components/lib/cJSON -I../Components/connectivity/mqtt/MQTTPacket/src -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Components/net/lwip/lwip_port/arch -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Components/net/lwip/lwip-2.1.2/src/core/ipv6/mld6.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Components/net/lwip/lwip-2.1.2/src/core/ipv6/nd6.o: ../Components/net/lwip/lwip-2.1.2/src/core/ipv6/nd6.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F107xC -DDEBUG -c -I../Middlewares/LiteOS/kernel/extended/include -I../Middlewares/LiteOS/arch/arm/arm-m/include -I../Components/connectivity/mqtt/MQTTClient-C/src -I../Components/Inc/fs -I../Components/connectivity/mqtt/MQTTClient-C/src/liteOS -I../Components/Inc -I../Middlewares/LiteOS/arch/arm/include -I../Middlewares/LiteOS/kernel/base/include -I../App/Inc -I../Components/net/lwip/lwip_port -I../Components/net/lwip/lwip_port/OS -I../Components/net/lwip/lwip-2.1.2/src/include -I../OS_CONFIG -I../Middlewares/LiteOS/kernel/include -I../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../Drivers/CMSIS/Include -I../Core/Inc -I../Hardware/Inc -I../Components/lib/cJSON -I../Components/connectivity/mqtt/MQTTPacket/src -I../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../Drivers/STM32F1xx_HAL_Driver/Inc -I../Components/net/lwip/lwip_port/arch -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Components/net/lwip/lwip-2.1.2/src/core/ipv6/nd6.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

